# Generated by Django 5.2.4 on 2025-07-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='rewards/')),
                ('description', models.TextField()),
                ('discount', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('upi', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='RewardSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.reward')),
            ],
        ),
    ]
